### ISSUE TITLE
Variable scope is not correct

### ISSUE THREAD

**Issue by karupanerura** [karupanerura/google-cloud-workflow-emulator#3]
The return value should be `[1, 2, 3]` but actual `[]`.

```yaml
---
main:
  params: [args]
  steps:
    - init:
        assign:
        - results: []
    - loop:
        for:
          value: i
          in: [1, 2, 3]
          steps:
            - append:
                assign:
                - results: '${list.concat(results, i)}'
    - final:
        return: '${results}'
```
